-- show references with Telescope, much better to see the context
vim.lsp.handlers["textDocument/references"] = function(_, _, _) require("telescope.builtin").lsp_references() end
vim.lsp.handlers["textDocument/implementation"] = function(_, _, _) require("telescope.builtin").lsp_implementations() end

-- tune up parameters for Go LSP
require("lspconfig").gopls.setup {
  single_file_support = true,
  settings = {
    gopls = {
      usePlaceholders = false,
      completeFunctionCalls = false,
      symbolScope = "all",
      symbolStyle = "Dynamic",
      symbolMatcher = "FastFuzzy",
      importShortcut = "Both",
      hoverKind = "FullDocumentation", -- or "SynopsisDocumentation", "SingleLine"
      completeUnimported = true,
      experimentalPostfixCompletions = true,
      staticcheck = true,
      gofumpt = true,
      diagnosticsDelay = "1s",
      diagnosticsTrigger = "Edit",
      analysisProgressReporting = true,
      codelenses = {
        tidy = true,
        generate = true,
        upgrade_dependency = true,
      },
      hints = {
        assignVariableTypes = true,
        compositeLiteralFields = true,
        compositeLiteralTypes = true,
        constantValues = true,
        functionTypeParameters = false,
        parameterNames = false,
        rangeVariableTypes = true,
      },
      analyses = {
        unusedparams = true,
        unusedvariable = true,
        assign = true,
        atomic = true,
        bools = true,
        composites = true,
        copylocks = true,
        defers = true,
        deprecated = true,
        directive = true,
        embed = true,
        errorsas = true,
        fillreturns = true,
        httpresponse = true,
        ifaceassert = true,
        infertypeargs = true,
        loopclosure = true,
        lostcancel = true,
        nilfunc = true,
        nilness = true,
        nonewvars = true,
        noresultvalues = true,
        printf = true,
        shadow = true, -- MAYBE NOT
        shift = true,
        sigchanyzer = true,
        simplifycompositelit = true,
        simplifyrange = true,
        simplifyslice = true,
        sortslice = true,
        stdmethods = true,
        stringintconv = true,
        structtag = true,
        testinggoroutine = true,
        tests = true,
        timeformat = true,
        unmarshal = true,
        unreachable = true,
        unsafeptr = true,
        unusedresult = true,
        unusedwrite = true,
        useany = true,
      },
      annotations = {
        bounds = true,
        escape = true,
        inline = true,
        -- 'nil' = true,
      },
    },
  },
}
